version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: sql-server
    environment:
      MYSQL_USER: users
      MYSQL_PASSWORD: pw123123
      MYSQL_ROOT_PASSWORD: pw123123
      MYSQL_DB: mydb
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
    - "3306:3306"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
      
    